# Generated by Django 5.2 on 2025-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('phone', models.IntegerField()),
                ('poste', models.TextField()),
            ],
        ),
    ]
